#!/usr/bin/env bash

#######################################################
# Checks time on all machines of the cluster.
# 
# Use as template for new scripts that have to be
# executed on all hosts at the same time.
#######################################################

COMMAND='date +"%Y-%m-%d %H:%M:%S"'
HOSTS='
  master01.bigdata
  worker01.bigdata
  worker02.bigdata
  lab01.bigdata
  lab02.bigdata
'

# Check own time
eval $COMMAND 2>&1 | sed "s/^/$HOSTNAME: /"

# Check time on remote hosts
for host in ${HOSTS}; do
  ssh $host $COMMAND 2>&1 | sed "s/^/$host: /" &
done
wait
